- name: Demo on condition
  hosts: localhost
  connection: local
  tasks:
    - name: Print Hello Universe
      ansible.builtin.debug:
        msg: Hello Universe
      when: what == "universe"

    - name: Print Hello World
      ansible.builtin.debug:
        msg: Hello World
      when: what == "world"

